name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  macos:
    strategy:
      matrix:
        target: [macos-universal-10.15]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  pluginval:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          target: pluginval
          pawpaw: true
